language: node_js #设置语言
node_js: node

# 缓存node_modules文件夹，节省部署的时间
#cache:
# directories:
# - node_modules

# 源码所在分支
branches:
only:
- master

# 安装依赖
install:
- npm install

# 执行的命令
script:
- hexo clean
- hexo generate

after_script:
  - cd ./public
  - git init
  - git config user.name "summerYard"
  - git config user.email "274948052@qq.com"
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://github.com/summerYard/summerYard.github.io.git" master:master

# 部署
#deploy:
#provider: pages
#skip-cleanup: true
#keep-history: true
#local-dir: public
#repo: summerYard/summerYard.github.io.git # 你的GitHub Page仓库地址
#target-branch: master