menu:
  - name: home
    url: /
    newTab: false
  #- name: code
    #url: /categories/code
    #newTab: true
  #- name: life
    #url: /categories/life
    #newTab: true
  #- name: read
    #url: /categories/read
    #newTab: true
  #- name: archive
    #url: /archive
    #newTab: true
  #- name: tag
    #url: /tags
    #newTab: true
  #- name: about
    #url: /about
    #newTab: false

widgets:
  #- user-info
  - toc
  - latest
  #- category
  - archive
  - label

favicon: /images/header.jpg

#UserInfo
avatar: /images/header.jpg
author: 不知道叫什么的空间……
slogan: 记录一些东西……